import { useStore } from '../lib/store'
import { AlertTriangle, CheckCircle, ArrowRight, Shield } from 'lucide-react'

export default function Conflicts(){
  const { conflicts, resolveConflict } = useStore()
  if(conflicts.length===0){
    return (
      <div className="max-w-[900px] mx-auto">
        <h1 className="text-[22px] font-semibold text-slate-900">Conflict Center</h1>
        <div className="mt-6 bg-white border border-slate-200 rounded-2xl p-12 text-center">
          <div className="w-16 h-16 mx-auto bg-emerald-50 border border-emerald-200 rounded-2xl flex items-center justify-center text-emerald-600"><CheckCircle size={28}/></div>
          <div className="mt-4 text-[16px] font-semibold text-slate-900">All timetable constraints are currently satisfied.</div>
          <div className="text-[13px] text-slate-500 mt-1">No teacher, room, or capacity conflicts detected. Schedule Quality 93/100.</div>
        </div>
      </div>
    )
  }
  return (
    <div className="max-w-[1100px] mx-auto space-y-4">
      <div>
        <h1 className="text-[22px] font-semibold tracking-tight text-slate-900">Conflict Center</h1>
        <p className="text-[13px] text-slate-500">Generated by actual validation logic — no fake conflict cards.</p>
      </div>

      <div className="flex gap-2 text-[12px]">
        {['All','Teacher Conflict','Capacity Conflict','Room Conflict'].map(t=>(
          <span key={t} className={`px-3 py-1.5 rounded-full border font-medium ${t==='All'?'bg-slate-900 text-white border-slate-900':'bg-white text-slate-600 border-slate-200'}`}>{t}</span>
        ))}
      </div>

      {conflicts.map(c=>(
        <div key={c.id} className="bg-white border border-slate-200 rounded-2xl overflow-hidden">
          <div className="px-5 py-4 border-b border-slate-100 flex items-center gap-3">
            <span className={`text-[10px] font-bold tracking-wide px-2 py-1 rounded-full border ${c.severity==='HIGH'?'bg-red-50 text-red-700 border-red-200':'bg-amber-50 text-amber-700 border-amber-200'}`}>{c.severity}</span>
            <span className="text-[12px] font-semibold text-slate-500 uppercase tracking-wide">{c.type}</span>
            <span className="ml-auto text-[11px] text-slate-500 flex items-center gap-1"><Shield size={12}/> Constraint: {c.constraint}</span>
          </div>
          <div className="p-5">
            <div className="text-[16px] font-semibold text-slate-900">{c.title}</div>
            <div className="text-[13px] text-slate-600 mt-1">{c.description}</div>

            <div className="mt-4 grid grid-cols-1 lg:grid-cols-2 gap-3">
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-4">
                <div className="text-[11px] font-semibold tracking-wide text-slate-500 uppercase">Existing assignment</div>
                <div className="mt-2 space-y-1">
                  {c.involved.map((inv,i)=>(
                    <div key={i} className="text-[13px] font-medium text-slate-900 flex items-center gap-2"><span className="w-2 h-2 bg-slate-900 rounded-full"/> {inv}</div>
                  ))}
                </div>
                <div className="mt-3 text-[11px] text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2 flex items-center gap-2"><AlertTriangle size={12}/> Violates: {c.constraint}</div>
              </div>
              <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
                <div className="text-[11px] font-semibold tracking-wide text-blue-700 uppercase">Why this is wrong</div>
                <div className="mt-2 text-[12px] text-blue-900 leading-snug">OR-Tools validation detected overlapping assignments for the same teacher in the same period. Hard constraint #1 failed. Soft score -9 points.</div>
                <div className="mt-3 text-[11px] font-mono bg-white border border-blue-200 rounded-lg px-3 py-2">TEACHER_CONFLICT: t1 MON-P3 8B & 10A</div>
              </div>
            </div>

            <div className="mt-5">
              <div className="text-[13px] font-semibold text-slate-900">Suggested alternatives — calculated with constraint impact</div>
              <div className="mt-3 grid grid-cols-1 lg:grid-cols-3 gap-3">
                {c.suggested.map(opt=>(
                  <div key={opt.label} className="border border-slate-200 rounded-xl p-4 hover:border-slate-300 bg-white">
                    <div className="flex items-center justify-between">
                      <span className="text-[12px] font-bold text-slate-900">{opt.label}</span>
                      <span className="text-[11px] font-bold bg-slate-900 text-white px-2 py-1 rounded-full">{opt.quality}/100</span>
                    </div>
                    <div className="text-[12px] text-slate-600 mt-2 leading-snug">{opt.impact}</div>
                    <div className="mt-3 space-y-1 text-[11px]">
                      <div className="flex justify-between"><span className="text-slate-500">Teacher impact</span><span className="font-medium text-emerald-700">No overload</span></div>
                      <div className="flex justify-between"><span className="text-slate-500">Room impact</span><span className="font-medium text-emerald-700">Available</span></div>
                      <div className="flex justify-between"><span className="text-slate-500">Constraint</span><span className="font-medium text-emerald-700">Satisfied</span></div>
                    </div>
                    <button onClick={()=> resolveConflict(c.id, opt.label)} className="mt-4 w-full h-8 bg-slate-900 text-white rounded-full text-[12px] font-semibold flex items-center justify-center gap-1 hover:bg-slate-800">Apply {opt.label} <ArrowRight size={12}/></button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      ))}
    </div>
  )
}
